### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by CySxL** [SparkDev97/Myriad-Bug-Tracker#19]
**Setup:**
1. What device are you using?
iPhone 11 Pro Max

2. What version of iOS is the device running?
iOS14.5.1

3. What jailbreak are you using (and what version)?
Unc0ver 7.0.2 with Fugu14

4. Have you tried disabling all other tweaks in iCleaner pro? Does the issue persist after doing this?
Yes. The issue is still there.

5. If yes to above: Try to narrow down the conflicting tweak by re-enabling tweaks one at a time. What tweak caused the issue to happen?
6. If it is a crash, please attach a crash log below (Use CrashReporter from repo: https://revulate.dev)
No crash at all.

**Steps to reproduce the bug:**
1. Install Telegram app from appstore
2. launch Telegram with SplitView
3.See the bottom of the app can't be displayed. So user can't type anything.
...

**What did you expect to happen?**
Showing the bottom part of the app correctly.

**What actually happened?**
The bottom part of the app disappears. So I can't send message to anyone because there isn't the text box.

**Further Information (screenshots, crash logs, etc)**
https://i.imgur.com/irBJp8x.jpg

**Comment by CySxL** [comment]
Dead project like others...

**Comment by SparkDev97** [comment]
Far from it. Wait for a public iOS 15 jb.

**Comment by CySxL** [comment]
> Far from it. Wait for a public iOS 15 jb. 

Got it. But does this means the issue is completed as you closed it ?
