### ISSUE TITLE
Homescreen and App Switcher Become Unresponsive

### ISSUE THREAD

**Issue by CRKatri** [SparkDev97/Myriad-Bug-Tracker#5]
Setup:
1.	What device are you using?  iPhone XR
2.	What version of iOS is the device running?  iOS 13.3
3.	What jailbreak are you using (and what version)?  Unc0ver 4.3.1
4.	Have you tried disabling all other tweaks in iCleaner pro? Does the issue persist after doing this?  Yes, issue persists.
5.	If yes to above: Try to narrow down the conflicting tweak by re-enabling tweaks one at a time. What tweak caused the issue to happen?  N/A
6.	If it is a crash, please attach a crash log below (Use CrashReporter from repo: https://revulate.dev)  Not a crash
Steps to reproduce the bug:
One of many ways
1. Open app in windowed mode
2. Open Spotlight
What did you expect to happen?  Homescreen and App Switcher to respond to touches
What actually happened?  They didn’t 
Further Information (screenshots, crash logs, etc) Apps Still respond as well as Control Center and Homebar actions

**Comment by SparkDev97** [comment]
This will be fixed in 0.3.1~Beta 2 (coming today).
