### ISSUE TITLE
[iPad] Apps open in windows but inside window app is sideways

### ISSUE THREAD

**Issue by diamkil** [SparkDev97/Myriad-Bug-Tracker#6]
**Setup:**
1. What device are you using? iPad 6th Generation
2. What version of iOS is the device running? 13.2.3
3. What jailbreak are you using (and what version)? Checkra1n 0.9.8
4. Have you tried disabling all other tweaks in iCleaner pro? Does the issue persist after doing this?
5. If yes to above: Try to narrow down the conflicting tweak by re-enabling tweaks one at a time. What tweak caused the issue to happen?
6. If it is a crash, please attach a crash log below (Use CrashReporter from repo: https://revulate.dev)

**Steps to reproduce the bug:**
1.  Launch app
2.  Switch app to myriad
3.
...

**What did you expect to happen?**

**What actually happened?**

**Further Information (screenshots, crash logs, etc)**

**Comment by SparkDev97** [comment]
I cannot reproduce this, I will need more information.

Did you launch the app from landscape? Does it happen with all applications or just some specific ones?

**Comment by diamkil** [comment]
Launched from landscape and happened to every app I tested, I have two bugs actually

**Comment by diamkil** [comment]
![7DA3812B-4B4D-4ED0-895D-C07D1114EAE7](https://user-images.githubusercontent.com/35732047/78586475-7fa85b00-7809-11ea-93c2-3c470e798393.png)
Can’t move apps since the app name is merged, app doesn’t take full window space and is in the wrong orientation

**Comment by SparkDev97** [comment]
Hmm last I checked it was working fine on iPad, but I will double check it on my iPad Pro.

**Comment by diamkil** [comment]
With latest updates this bug is fixed although I found a new one and will open a new issue for it
